name: dynamic_cached_fonts_example
description: An example app to demonstrate the use of dynamic_cached_fonts.

publish_to: 'none'
version: 1.0.0

dependencies:
  flutter:
    sdk: flutter

  dynamic_cached_fonts:
    path: ../
  firebase_core: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lint: ^1.5.3

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.20.0 <3.0.0"

flutter:
  uses-material-design: true
