version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "internal: dependencies ⬆➕"

  - package-ecosystem: "pub"
    directory: "/example"
    schedule:
      interval: "weekly"
    labels:
      - "example"
      - "internal: dependencies ⬆➕"
