example:
  - any: ['example/**/*']
    all: ['!CHANGELOG.md']

'infra :building_construction:':
  - .github/workflows/*
  - .github/*.yml
  - dev/ci/*
  - dev/docker/*
  - docker-compose.yml
  - analysis_options.yml
  - example/analysis_options.yml
  - dartdoc_options.yml
  - '**/README.md'
  - CODE_OF_CONDUCT.md
  - LICENSE
  - .github/ISSUE_TEMPLATE/*
  - .github/PULL_REQUEST_TEMPLATE.md

'infra: ci :construction_worker:':
  - .github/workflows/*
  - .github/*.yml
  - dev/ci/*

'infra: development-experience :children_crossing:':
  - dev/docker/*
  - docker-compose.yml
  - analysis_options.yml
  - example/analysis_options.yml
  - dartdoc_options.yml

'infra: community':
  - '**/README.md'
  - CODE_OF_CONDUCT.md
  - LICENSE
  - .github/ISSUE_TEMPLATE/*
  - .github/PULL_REQUEST_TEMPLATE.md

'internal: dependencies ⬆➕':
  - any: ['**/pubspec*']
    all: ['!CHANGELOG.md']

'test :rotating_light:':
  - example/test_driver/*
  - example/integration_test/*
  - test/*

'test: integration-test':
  - example/test_driver/*
  - example/integration_test/*

'test: unit-test': test/*

'internal: style :nail_care:': '**/analysis_options.yaml'

'documentation :book:':
  - '**/doc/*'
  - '**/dartdoc_options.yaml'

# 'release :tada:', 'revert :rewind:' - Defined in .github/workflows/labler.yml
