example: example/**/*

'infra :building_construction:':
  - .github/workflows/*
  - Docker
  - docker-compose.yml
  - analysis_options.yml
  - example/analysis_options.yml
  - dartdoc_options.yml
  - '**/README.md'
  - CODE_OF_CONDUCT.md
  - LICENSE
  - .github/ISSUE_TEMPLATE/*
  - .github/PULL_REQUEST_TEMPLATE.md

'infra: ci :construction_worker': .github/workflows/*

'infra: development-experience :children_crossing:':
  - Docker
  - docker-compose.yml
  - analysis_options.yml
  - example/analysis_options.yml
  - dartdoc_options.yml

'infra: community':
  - '**/README.md'
  - CODE_OF_CONDUCT.md
  - LICENSE
  - .github/ISSUE_TEMPLATE/*
  - .github/PULL_REQUEST_TEMPLATE.md

'internal: dependencies ⬆➕':
  - any: ['**/pubspec.yaml']
    all: ['!CHANGELOG.md']

'release :tada:': CHANGELOG.md

'test :rotating_light:':
  - example/test_driver/*
  - example/integration_test/*
  - test/*

'test: integration-test': 
  - example/test_driver/*
  - example/integration_test/*

'test: unit-test': test/*
