---
include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false

linter:
  rules:
    curly_braces_in_flow_control_structures: false
    avoid_equals_and_hash_code_on_mutable_classes: true
    literal_only_boolean_expressions: true
    sort_constructors_first: true
    public_member_api_docs: true
    prefer_single_quotes: true
    prefer_final_locals: true
    prefer_final_fields: true
    prefer_const_declarations: true
    prefer_const_constructors: true
    use_named_constants: true
