version: "3.9"
services:
  windows:
    build:
      context: .
      dockerfile: dev/docker/Dockerfile.windows
    image: sidrao2006/flutter-desktop-windows
    volumes:
      - .:/app
      - /root/.pub-cache
      - /app/.dart_tool
      - /app/example/.dart_tool

  linux:
    build:
      context: .
      dockerfile: dev/docker/Dockerfile.linux
    image: sidrao2006/flutter-desktop-linux
    volumes:
      - .:/app
      - pub-cache:/root/.pub-cache
      - dart-tool:/app/.dart_tool
      - example-dart-tool:/app/example/.dart_tool

volumes:
  pub-cache:
  dart-tool:
  example-dart-tool:
