name: Code Analysis
on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  pana_analyze:
    name: Analyze package with Pana
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Analyze package with pana
        uses: axel-op/dart-package-analyzer@v3
        id: analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate Result
        env:
          PUB_SCORE_MIN_POINTS: 90
          SCORE: ${{ steps.analysis.outputs.total }}
        if: ${{ env.SCORE < env.PUB_SCORE_MIN_POINTS }}
        run: |
          echo "::error::Pub score test failed. Achieved score of $SCORE is less than expected minimum score of $PUB_SCORE_MIN_POINTS"
