name: Code Analysis
on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  pana_analyze:
    name: Analyze package with Pana
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: beta

      - name: Get flutter packages
        run: dart pub get
      
      - name: Format code for tests
        run: dart format .
      
      - name: Run pana tests
        run: |
          echo 'PANA_RESULT_JSON<<EOF' >> $GITHUB_ENV
          dart run pana . --json --no-warning >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install node dependencies
        run: npm install cli-markdown @actions/core

      - name: Calculate Result
        run: node dev/ci/code_analysis.js
        env:
          PUB_SCORE_MIN_POINTS: 90
