name: Code Analysis
on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  pana_analyze:
    name: Analyze package with Pana
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: beta

      - name: Get flutter packages
        run: flutter pub get

      - name: Activate pana
        run: flutter pub global activate pana ^0.16.0
      
      - name: Format code for tests
        run: flutter format .
      
      - name: Run pana tests
        id: test
        run: |
          echo "::set-output name=panaOutput::$(flutter pub global run pana . --json --no-warning)"

      - name: Calculate Result
        env:
          PUB_SCORE_MIN_POINTS: 90
          PANA_RESULT_JSON: ${{ steps.test.outputs.panaOutput }}
        uses: actions/github-script@v3
        with:
          script: |
            const output = JSON.parse(process.env.PANA_RESULT_JSON),
              minScore = Number.parseInt(process.env.PUB_SCORE_MIN_POINTS)
            const score = output.scores.grantedPoints,
              sections = output.report.sections;

            if (score < minScore) {
               for (const testJson in sections) {
                  const test = JSON.parse(testJson)
                  if (test.status !== 'passed') core.warning(test.title + '\n\n\n' + test.summary)
               }
               core.setFailed(`Pub score test failed. Achieved score of ${score} is less than expected minimum score of ${minScore}`)
            }
