name: Documentation Analysis
on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  dartdoc_analysis:
    name: Documentation Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: beta
      
      - name: Get flutter packages
        run: flutter pub get
        
      - name: Activate dartdoc
        run: flutter pub global activate dartdoc
      
      - name: Run dartdoc
        run: flutter pub global run dartdoc . --no-generate-docs -q

   