name: Documentation Analysis
on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  dartdoc_analysis:
    name: Documentation Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: beta
      
      - name: Get flutter packages
        run: dart pub get
        
      - name: Activate dartdoc
        run: dart pub global activate dartdoc
      
      - name: Run dartdoc
        run: dart pub global run dartdoc . --no-generate-docs -q

   