name: Integration Tests
on: 
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  chrome_integration_test:
    name: Web Integration Test
    environment: integration_tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: example

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: beta

      - name: Setup Chrome Driver
        uses: nanasess/setup-chromedriver@master

      - name: Get flutter packages
        run: flutter pub get

      - name: Browser pre launch Setup
        run: |
          sudo apt-get install -y xvfb
          sudo apt-get -y install xorg xvfb gtk2-engines-pixbuf
          sudo apt-get -y install dbus-x11 xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic xfonts-scalable
          sudo apt-get -y install imagemagick x11-apps

      - name: Run integration tests
        run: |
          Xvfb -ac :99 -screen 0 1280x1024x16 & export DISPLAY=:99

          chromedriver --port=4444 &

          flutter driver --driver test_driver/integration_test.dart \
          --target ./integration_test/dynamic_cached_fonts_example_test.dart \
          --browser-name chrome \
          --dart-define FIREBASE_STORAGE_FONT_URL=$FIREBASE_STORAGE_FONT_URL \
          --release
        env:
          FIREBASE_STORAGE_FONT_URL: ${{ secrets.FIREBASE_STORAGE_FONT_URL }}

  firebase_test_lab_android_integration_test:
    name: Firebase Test Lab Android Integration Test
    environment: integration_tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: beta

      - name: Get flutter packages
        run: flutter pub get

      - name: Build android instrumentation test 
        working-directory: example
        run: |
          pushd android
          # flutter build generates files in android/ for building the app
          flutter build apk
          ./gradlew app:assembleAndroidTest
          ./gradlew app:assembleDebug -Ptarget=$GITHUB_WORKSPACE/example/integration_test/dynamic_cached_fonts_example_test.dart
          popd
      
      - name: Set up Google Cloud SDK for Firebase
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      
      - name: Upload APKs to Firebase Test Lab
        working-directory: example
        run: |
          gcloud firebase test android run --type instrumentation \
            --app build/app/outputs/apk/debug/app-debug.apk \
            --test build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk\
            --timeout 2m \
