name: Integration Tests
on: 
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  chrome_integration_test:
    name: Web Integration Test
    environment: Web Desktop Integration Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: example

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: beta

      - name: Setup Chrome Driver
        uses: nanasess/setup-chromedriver@master

      - name: Run integration tests
        run: |
          export DISPLAY=:99

          chromedriver --port=4444 &

          flutter driver --driver test_driver/integration_test.dart \
          --target ./integration_test/dynamic_cached_fonts_example_test.dart \
          --dart-define FIREBASE_STORAGE_FONT_URL=$FIREBASE_STORAGE_FONT_URL \
          --device-id web-server \
          --browser-name chrome \
          --release
        env:
          FIREBASE_STORAGE_FONT_URL: ${{ secrets.FIREBASE_STORAGE_FONT_URL }}

  android_integration_test:
    name: Android Integration Test (Firebase Test Lab)
    environment: Mobile Integration Tests
    runs-on: ubuntu-latest

    steps:
      - run: exit 1
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: beta

      - name: Build android instrumentation test 
        working-directory: example
        run: |
          pushd android
          # flutter build generates files in android/ for building the app
          flutter build apk
          ./gradlew app:assembleAndroidTest
          ./gradlew app:assembleDebug -Ptarget=$GITHUB_WORKSPACE/example/integration_test/dynamic_cached_fonts_example_test.dart
          popd
      
      - name: Set up Google Cloud SDK for Firebase
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      
      - name: Upload APKs to Firebase Test Lab
        working-directory: example
        run: |
          gcloud firebase test android run --type instrumentation \
            --app build/app/outputs/apk/debug/app-debug.apk \
            --test build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk\
            --timeout 2m \

  ios_integration_test:
    name: iOS Integration Test
    environment: Mobile Integration Tests
    runs-on: macos-latest

    defaults:
      run:
        working-directory: example

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: beta

      - name: Run tests on simulator
        run: |
          flutter emulators --launch apple_ios_simulator
          
          flutter test \
            --dart-define FIREBASE_STORAGE_FONT_URL=$FIREBASE_STORAGE_FONT_URL \
            --device-id iPhone \
            ./integration_test/dynamic_cached_fonts_example_test.dart

  desktop_integration_test:
    name: ${{ matrix.name }} Integration Test
    environment: Web Desktop Integration Test
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux (Ubuntu)
            flutter_os: linux

          - os: windows-latest
            name: Windows
            flutter_os: windows

          - os: macos-latest
            name: MacOS
            flutter_os: macos

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: example
        shell: pwsh

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: beta

      - name: Configure Flutter platforms
        run: flutter config --enable-${{ matrix.flutter_os }}-desktop

      - name: Setup Linux Environment
        if: ${{ matrix.os == 'ubuntu-latest' }}
        # Remaining dependencies are pre-installed
        run: |
          sudo apt-get -y --no-install-recommends install `
          libgtk-3-dev `
          liblzma-dev `
          ninja-build `
          xvfb

      - name: Run Integration Tests
        env:
          OS: ${{ matrix.os }}
        run: |
         if ( "$env:OS" -eq "ubuntu-latest" ) { Xvfb -ac :99 &; $env:DISPLAY=":99" }

          flutter driver --driver test_driver/integration_test.dart --target ./integration_test/dynamic_cached_fonts_example_test.dart --dart-define FIREBASE_STORAGE_FONT_URL=$FIREBASE_STORAGE_FONT_URL --device-id ${{ matrix.flutter_os }}
