name: Github Pages Example
on:
  push:
    branches:
      - main
    paths:
      - 'example/web/**'
      - 'example/pubspec.*'
      - 'example/lib/**'
  workflow_dispatch:

concurrency:
  group: Example Github Pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    name: Build and Deploy Example to Github Pages
    uses: sidrao2006/workflows/.github/workflows/flutter_gh_pages_deploy.yml@v1
    with:
      dir: example
      environment: Example Github Pages
      job_name: Build and Deploy Example to Github Pages # same as jobs.<job_id>.name
    secrets:
      args: --dart-define FIREBASE_STORAGE_FONT_URL=${{ secrets.FIREBASE_STORAGE_FONT_URL }}

    permissions:
      contents: write
