name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  triage:
    name: Add PR labels
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true