name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  triage:
    name: Add PR labels
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true

      - name: Add 'revert' label to relevant PRs
        uses: actions/github-script@v4
        with:
          script: |
            github.pulls
              .get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
              })
              .then(({ data: pr }) => {
                if (pr.title.includes("Revert")) {
                  github.issues.addLabels({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: context.payload.pull_request.number,
                    labels: ['revert :rewind:'],
                  });
                }
              });

      - name: Add 'release' label to relevant PRs
        uses: actions/github-script@v4
        with:
          script: |
            const requiredFiles = [ 'CHANGELOG.md', 'pubspec.yaml', 'example/pubspec.lock' ]

            const listFilesOptions = github.pulls.listFiles.endpoint.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const listFilesResponse = await github.paginate(listFilesOptions);
            const changedFiles = listFilesResponse.map((f: any) => f.filename);

            if ( requiredFiles.every(file => changedFiles.includes(file)) ) {
              github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: ['release :tada:'],
              });
            }
