name: Unit Tests
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  unit_test:
    name: Unit Test
    uses: sidrao2006/workflows/.github/workflows/flutter_unit_test.yml@v1
