name: Unit Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: beta

      - name: Run unit tests
        run: flutter test
