name: Release and publish package
on:
  push:
    branches: [main]
    paths:
      - 'CHANGELOG.md'
  workflow_dispatch:

concurrency:
  group: Release
  cancel-in-progress: true

jobs:
  release:
    name: Release and Publish Package
    uses: sidrao2006/workflows/.github/workflows/pub_release.yml@v2
    with:
      environment: Release
      job_name: Release and Publish Package # same as jobs.<job_id>.name

    permissions:
      contents: write
      id-token: write
