name: Release and publish package
on:
  push:
    branches: [main]
    paths:
      - 'CHANGELOG.md'
  workflow_dispatch:

concurrency:
  group: Release
  cancel-in-progress: true

jobs:
  release:
    name: Release and Publish Package
    uses: sidrao2006/workflows/.github/workflows/pub_release.yml@v1
    with:
      environment: Release
      job_name: Release and Publish Package # same as jobs.<job_id>.name
    secrets:
      PUB_CREDENTIALS_ACCESS_TOKEN: ${{ secrets.PUB_CREDENTIALS_ACCESS_TOKEN }}
      PUB_CREDENTIALS_REFRESH_TOKEN: ${{ secrets.PUB_CREDENTIALS_REFRESH_TOKEN }}
      PUB_CREDENTIALS_ID_TOKEN: ${{ secrets.PUB_CREDENTIALS_ID_TOKEN }}
      PUB_CREDENTIALS_TOKEN_ENDPOINT: ${{ secrets.PUB_CREDENTIALS_TOKEN_ENDPOINT }}
      PUB_CREDENTIALS_EXPIRATION: ${{ secrets.PUB_CREDENTIALS_EXPIRATION }}

    permissions:
      contents: write
